import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../component/NavBar";
import LearnHooks from "./LearnHooks";
import LearnUseEffect from "./LearnUseEffect";
import LearnUseReducer from "./LearnUseReducer";
import LearnUseRef from "./LearnUseRef";
import LearnUseLayout from "./LearnUseLayout";
import LearnUseMem0 from "./LearnUseMem0";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <LearnHooks />
        <LearnUseEffect /> */}

        {/* <LearnUseReducer /> */}
        {/*  <LearnUseRef /> */}

        {/* <LearnUseLayout /> */}
        <LearnUseMem0 />

        {children}
      </body>
    </html>
  );
}
